version: '3.9'

services:

  api:
    image: minha-api
    restart: always
    ports:  
      - 8000:8000
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://usuario:cloudteste123@db:5432/meu_banco}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres
    hostname: db
    restart: always
    environment:
      POSTGRES_USER: ${MEUUSUARIO:-usuario}
      POSTGRES_PASSWORD: ${MINHASENHADB:-cloudteste123}
      POSTGRES_DB: ${POSTGRES_BANCO:-meu_banco}
