version: '3.9'

services:

  api:
    image: minha-api
    restart: always
    ports:  
      - 8000:8000
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres
    hostname: db
    restart: always
    environment:
      POSTGRES_USER: ${MEUUSUARIO}
      POSTGRES_PASSWORD: ${MINHASENHADB}
      POSTGRES_DB: ${POSTGRES_BANCO}
