name: cloud

services:

  web:
    build:
      dockerfile_inline: |
        FROM nginx:latest
        COPY ./nginx.conf /etc/nginx/nginx.conf
    image: nginx:latest
    ports:
      - 8080:80


  api:
    hostname: api
    build:
      context: ./api
      dockerfile: Dockerfile

      deploy:
        replicas: 1
      enviroments:
        POSTGRES_PASSWORD: ${MINHASENHADB}

